# Generated by Django 4.1.5 on 2023-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmyticketapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
