# Generated by Django 4.1.5 on 2023-01-08 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookmyticketapi", "0003_genre_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinema",
            options={"ordering": ["city", "name"]},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["created", "title"]},
        ),
        migrations.AlterModelOptions(
            name="moviebooking",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="movieshow",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="screen",
            options={"ordering": ["cinema", "number"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="cinema",
            name="address",
            field=models.TextField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cinema",
            name="city",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="bookmyticketapi.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cinema",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moviebooking",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
