# Generated by Django 4.1.5 on 2023-01-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookmyticketapi", "0004_alter_cinema_options_alter_city_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.city",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.state",
            ),
        ),
        migrations.AlterField(
            model_name="moviebooking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.customer",
            ),
        ),
        migrations.AlterField(
            model_name="moviebooking",
            name="movie_show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.movieshow",
            ),
        ),
        migrations.AlterField(
            model_name="movieshow",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movieshow",
            name="screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.screen",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.cinema",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookmyticketapi.country",
            ),
        ),
    ]
