# Generated by Django 4.1.5 on 2023-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmyticketapi", "0005_alter_cinema_city_alter_city_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("name", "country")},
        ),
    ]
