# Generated by Django 4.1.5 on 2023-01-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookmyticketapi",
            "0006_alter_cinema_name_alter_city_name_alter_country_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "state")},
        ),
        migrations.AlterUniqueTogether(
            name="screen",
            unique_together={("number", "cinema")},
        ),
    ]
