# Generated by Django 4.1.5 on 2023-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookmyticketapi",
            "0007_alter_city_name_alter_genre_name_alter_movie_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
